### ISSUE TITLE
Understand the difference in counts, effective mu and MDP between the numerical integration and the MC code

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/ximpol#114]
An example for the Crab nebula, 10ks intergration

xpmdp.py output

```
>>> 1.00--2.80 keV: 10458769 counts in 10000 s, mu 0.149, MDP 0.89%
>>> 2.80--4.60 keV: 1609538 counts in 10000 s, mu 0.410, MDP 0.82%
>>> 4.60--6.40 keV: 164521 counts in 10000 s, mu 0.543, MDP 1.95%
>>> 6.40--8.20 keV: 24749 counts in 10000 s, mu 0.611, MDP 4.46%
>>> 8.20--10.00 keV: 3963 counts in 10000 s, mu 0.659, MDP 10.34%
```

xpbin.py output 

![mcube_table](https://cloud.githubusercontent.com/assets/8972541/14669876/106ca5e0-06eb-11e6-9c66-239927b1946d.png)

**Comment by ndilalla** [comment]
This is due to the effect of energy dispersion that is not taken in account in xpmdp. If we bin the sample using MC energy instead of smeared energy, we get consistent results for the two codes.

**Comment by lucabaldini** [comment]
Awesome. Well done---this needs to go in the documentation somewhere.

(Don't close the issue until we've written this in stone.)

**Comment by lucabaldini** [comment]
Can we add this to the documentation and close this one?

**Comment by lucabaldini** [comment]
Can we add this to the documentation and close this one?

**Comment by ndilalla** [comment]
Yes, we can. I put this one on top of my to-do list.

**Comment by lucabaldini** [comment]
Closing this one. Once we're documented the limitation of the application we can close issue #107 as well.
