### ISSUE TITLE
Find out the number of channels for XIPE

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/ximpol#13]
Also, the 1024 that we have right now is hard-coded in several places, and we should avoid that.

**Comment by csgro** [comment]
Not sure why you need the number of channels. Was the plan to keep only high-level information (direction, energy, time, polarization dir/angle)? 
Anyway, I totally agree on not having hard-coded number (in particular if they are wrong), but the detector will not change :)

**Comment by lucabaldini** [comment]
XSPEC understand energy dispersion in channel space. We do have to put this in if we want the response function in OGIP standard.

**Comment by csgro** [comment]
ok, sorry, I misinterpreted the concept of "channel". And yes it cannot be hard-coded.

**Comment by lucabaldini** [comment]
The hard-coded values should be eliminated. I set the number of channels to 256, which gives O(50) points for sampling our typical energy dispersion. We can revise that if needed.
