### ISSUE TITLE
Make sure the energy resolution in eres_fwhm_hedme8020_1atm_1cm.asc is ok

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/ximpol#14]
The values seem a little bit too small for them to be FWHM. Cross check with Fabio and Paolo.

**Comment by csgro** [comment]
For reference it should be ~20% FWHM at 5.9 keV (55Fe).
![edispersionexample](https://cloud.githubusercontent.com/assets/16150310/12119285/28915ef4-b3cb-11e5-8b25-e95e6a888ce1.png)

**Comment by lucabaldini** [comment]
#E [keV]FWHM [keV]
2.0 0.52
2.6     0.59
3.7     0.75
4.5     0.81
6.4     0.98
8.0     1.14

It is 18% at 4.5 keV and 15% at 6.4 keV. Does this make sense?

(At some point we should probably implement the left tail in the simulation.)

**Comment by csgro** [comment]
Hmm...a bit small, but not totally unreasonable. I guess they are ok for now, but we definitely need a better parametrization for the future.

**Comment by lucabaldini** [comment]
Ok, good as is for the time being.
