### ISSUE TITLE
Fix the "5 keV line" bug

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/ximpol#22]
When simulating a plain power law with index 2 we do have a single-bin feature in the count spectrum (at around 5 keV, the actual energy likely changing with the spectral index).

This is most likely connected with how we sample the ppf and might be fixed by working in log-log space.
![5kevline](https://cloud.githubusercontent.com/assets/8972541/12368598/c66009ae-bba1-11e5-8c82-48fc0fa49ae6.png)

**Comment by ndilalla** [comment]
This is due to an error in the count spectrum binning. I fixed this bug with:

```
@@ -252,7 +253,7 @@ class xEventBinningPHA1(xEventBinningBase):
         evt_header = self.event_file.hdu_list['PRIMARY'].header
         num_chans = evt_header['DETCHANS']
         total_time = self.event_file.total_good_time()
-        binning = numpy.linspace(-0.5, num_chans - 0.5, num_chans)
+        binning = numpy.linspace(-0.5, num_chans - 0.5, num_chans+1)
         n, bins = numpy.histogram(self.event_data['PHA'], bins=binning)
         primary_hdu = self.build_primary_hdu()
         data = [numpy.arange(num_chans),

```

Using the old binning, the bin intervals were slightly greater than one channel, so that the 127th bin (~5 keV) received counts coming from two different channels (doubling the content).

**Comment by ndilalla** [comment]
Done.
