### ISSUE TITLE
Implement extrapolation in xFunction1d

### ISSUE THREAD

**Issue by mpescerollins** [lucabaldini/ximpol#3]
The energy dispersion file has points only from 2- 8 keV. We need a method that permits one to extrapolate a function beyond the energy range provided. This so that we can have the energy dispersion in the full range 1-10 keV.

**Comment by lucabaldini** [comment]
Working on this. xFunction1d will be removed in favor of core.spline.xInterpolatedUnivariateSplineLinear

The code is ready. It just needs to be used.

**Comment by lucabaldini** [comment]
Code used throughout, old classes removed.
