### ISSUE TITLE
Make sure we got the PSF parametrization right

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/ximpol#31]
At a first glance it seems too narrow.

**Comment by lucabaldini** [comment]
In the IRF page
http://ximpol.readthedocs.io/en/latest/response_functions.html
we say
"""
For the XIPE baseline design we start by assuming a gaussian + King profile with a HEW of 15 arcsec, with the exact same parametrization and parameters values of Fabiani et al. (2014).
"""
see http://arxiv.org/abs/1403.7200

So we should double check that:
1\ we're using the exact same parameter values as in the paper;
2\ the radial plot we're obtaining is the same as the one in the paper;
3\ we get the right HEW (half-energy window) by direct integration of our PSF.

[I suspect that for 3\ there's something subtle connected with integration in 1d vs. 2d, but I should go back and check the definition of the HEW.]

**Comment by lucabaldini** [comment]
By the way, we should also consider how we use the PSF in the event generation, see ximpo/irf/psf.py

```
    def delta(self, size=1):
        """Return an array of random offset (in ra, dec or L, B) due to the PSF.

        Note the output is converted in degrees.
        """
        rho = self.rvs(size)/3600.
        phi = numpy.random.uniform(0, 2*numpy.pi, size)
        return rho*numpy.cos(phi), rho*numpy.sin(phi)
```

I believe we're assuming here that the solid angle is already included in the radial parametrization.

Maybe the definitive test would be to throw n enevts and make sure that the right fraction of them is included within 15 arcsec (in two dimensions).

**Comment by ndilalla** [comment]
I changed the psf function in this way:

```
-        _psf = W*numpy.exp(-(_r**2/(2*sigma**2))) + N*(1 + (_r/r_c)**2)**(-eta)
+        _psf = 2*numpy.pi*_r*(W*numpy.exp(-(_r**2/(2*sigma**2))) +\
+                                                   N*(1 + (_r/r_c)**2)**(-eta))
```

so that the HEW radius is now ~ 11 arcsec.

**Comment by lucabaldini** [comment]
I believe this is now fully under control.
