### ISSUE TITLE
bin/xpobssim.py should exit with an error message if IRFs are not found

### ISSUE THREAD

**Issue by csgro** [lucabaldini/ximpol#63]
Currently there is no protection and the code crashes with trying to open non existing files. Usually is the IRF name is misspelled. 
A few assert in the irf/**init**.py can make the explicit why the program exited.

**Comment by csgro** [comment]
Assert still gives a traceback, I prefer to exit silently with an explicit error message. 
Small changes to ximpol/irf/**init**.py

**Comment by lucabaldini** [comment]
Good point. To make this reusable, I made a small utility function in ximpol.utils.os_ and used in the relevant places.
